-- TABLA USUARIO
INSERT INTO `bibliotech_daw`.`user` (`username`, `email`, `name`, `password`, `role`) SELECT 'admin', 'admin@bibliotech.com', 'Administrador', SHA2('admin', 256), 'MOD';
INSERT INTO `bibliotech_daw`.`user` (`username`, `email`, `name`, `password`, `role`) SELECT 'user', 'user@bibliotech.com', 'Usuario', SHA2('user', 256), 'USER';

INSERT INTO `bibliotech_daw`.`user` (`username`, `email`, `image`, `name`, `password`, `role`) SELECT 'jfranav', 'jfranav@bibliotech.com', '1', 'Juan Francisco Navarra', SHA2('1234', 256), 'USER';
INSERT INTO `bibliotech_daw`.`user` (`username`, `email`, `image`, `name`, `password`, `role`) SELECT 'rsanord', 'rsanord@bibliotech.com', '2', 'Ramon Sandoval Ordóñez', SHA2('1234', 256), 'USER';
INSERT INTO `bibliotech_daw`.`user` (`username`, `email`, `image`, `name`, `password`, `role`) SELECT 'hbenpre', 'hbenpre@bibliotech.com', '3', 'Hugo Benítez Predrero', SHA2('1234', 256), 'USER';
INSERT INTO `bibliotech_daw`.`user` (`username`, `email`, `image`, `name`, `password`, `role`) SELECT 'avelang', 'avelang@bibliotech.com', '4', 'Alonso Vélez Anglés', SHA2('1234', 256), 'USER';

INSERT INTO `bibliotech_daw`.`user` (`username`, `email`, `image`, `name`, `password`, `role`) SELECT 'aisafon', 'aisafon@bibliotech.com', '6', 'Ana Isabel Fonz', SHA2('1234', 256), 'USER';
INSERT INTO `bibliotech_daw`.`user` (`username`, `email`, `image`, `name`, `password`, `role`) SELECT 'vcerhid', 'vcerhid@bibliotech.com', '7', 'Valentina Cerecero Hidalgo', SHA2('1234', 256), 'USER';
INSERT INTO `bibliotech_daw`.`user` (`username`, `email`, `image`, `name`, `password`, `role`) SELECT 'cmarobr', 'cmarobr@bibliotech.com', '8', 'Carmen María Obrero', SHA2('1234', 256), 'USER';
INSERT INTO `bibliotech_daw`.`user` (`username`, `email`, `image`, `name`, `password`, `role`) SELECT 'syanaba', 'syanaba@bibliotech.com', '9', 'Sandra Yáñez Abad', SHA2('1234', 256), 'USER';

INSERT INTO `bibliotech_daw`.`user` (`username`, `email`, `image`, `name`, `password`, `role`) SELECT 'adraraore', 'adraraore@bibliotech.com', '5', 'Adrian Arán Orellana', SHA2('1234', 256), 'MOD';
INSERT INTO `bibliotech_daw`.`user` (`username`, `email`, `image`, `name`, `password`, `role`) SELECT 'olgarrcas', 'olgarrcas@bibliotech.com', '10', 'Olga Arroyo Castrillón', SHA2('1234', 256), 'MOD';

-- TABLA CATEGORÍA
INSERT INTO `bibliotech_daw`.`category`(`image`, `name`) VALUES ('art', 'Artes y humanidades');
INSERT INTO `bibliotech_daw`.`category`(`image`, `name`) VALUES ('biography', 'Biografía');
INSERT INTO `bibliotech_daw`.`category`(`image`, `name`) VALUES ('science', 'Ciencias e Informática');
INSERT INTO `bibliotech_daw`.`category`(`image`, `name`) VALUES ('law', 'Ciencias Sociales y Derecho');
INSERT INTO `bibliotech_daw`.`category`(`image`, `name`) VALUES ('communication', 'Comunicación');
INSERT INTO `bibliotech_daw`.`category`(`image`, `name`) VALUES ('sport', 'Educación física');
INSERT INTO `bibliotech_daw`.`category`(`image`, `name`) VALUES ('factory', 'Ingeniería, Industria y Construcción');
INSERT INTO `bibliotech_daw`.`category`(`image`, `name`) VALUES ('languages', 'Idiomas');
INSERT INTO `bibliotech_daw`.`category`(`image`, `name`) VALUES ('history', 'Historia');
INSERT INTO `bibliotech_daw`.`category`(`image`, `name`) VALUES ('health', 'Salud y Servicios Sociales');

-- TABLA LIBRO
INSERT INTO `bibliotech_daw`.`book` (`ISBN`, `author`, `name`, `description`, `price`, `quantity`, `category_id`, `pages`, `publish_date`, `modified_at`, `created_at`) VALUES
('0008241775', 'Simon Winchester', 'Los perfeccionistas: Cómo la precisión creó el mundo moderno', 'El autor superventas Simon Winchester escribe una magnífica historia de los ingenieros pioneros que desarrollaron maquinaria de precisión para permitirnos ver tan lejos como la luna y tan cerca como el bosón de Higgs. La precisión es la clave de todo. Es un componente integral, indiscutible y esencial de nuestros paisajes sociales, mercantiles, científicos, mecánicos e intelectuales modernos. Los artículos que valoramos en nuestra vida diaria (una cámara, un teléfono, una computadora, una bicicleta, un automóvil, quizás un lavaplatos), todos componentes deportivos que encajan con precisión y funcionan casi a la perfección. También asumimos que cuanto más preciso es un dispositivo, mejor es. Y, sin embargo, mientras vivimos vidas salpicadas y untadas con precisión, cuando pensamos en ello, no estamos completamente seguros de qué es precisión o qué significa. ¿Cómo y cuándo se empezó a construir el mundo moderno?', 54, 2, 7, 336, '2018-06-10 00:00:00', NULL, '2022-04-30 19:27:27'),
('0060566108', 'James C. Collins', 'Empresas Que Perduran', '\"Este no es un libro sobre líderes visionarios carismáticos. No se trata de conceptos de productos visionarios o de productos visionarios o de perspectivas de mercado visionarias. Tampoco se trata simplemente de tener una visión corporativa. Este es un libro sobre algo mucho más importante, duradero y sustancial. Este es un libro sobre empresas visionarias\". Así escriben Jim Collins y Jerry Porras en este innovador libro que rompe mitos, brinda nuevos conocimientos y brinda orientación práctica a quienes deseen crear empresas emblemáticas que superen la prueba del tiempo.', 26, 2, 5, 368, '2004-11-02 00:00:00', NULL, '2022-04-30 19:16:18'),
('0300079397', 'Rudolf Wittkower', 'Arte y Arquitectura en Italia, 1600-1750', 'Este estudio clásico del arte y la arquitectura del barroco italiano se centra en las artes de todos los centros entre Venecia y Sicilia en los períodos barroco temprano, alto y tardío. El corazón del estudio, sin embargo, se encuentra en la arquitectura y la escultura de los emocionantes años del Alto Barroco Romano, cuando Bernini, Borromini y Cortona estaban trabajando bajo una serie de papas ilustrados. El texto de Wittkower ahora va acompañado de una introducción crítica y una nueva bibliografía sustancial. Esta edición también incluirá ilustraciones a color por primera vez.', 46, 3, 1, 132, '1999-10-11 00:00:00', NULL, '2022-04-30 20:00:00'),
('0306812835', 'J.E. Gordon', 'Estructuras: O por qué las cosas no se caen', 'Estructuras: o por qué las cosas no se caen es una explicación informal de las fuerzas básicas que mantienen unidas las cosas ordinarias y esenciales de este mundo, desde edificios y cuerpos hasta aviones voladores y cáscaras de huevo. En un estilo que combina ingenio, un dominio magistral de su tema y una variedad de referencias enciclopédicas, Gordon incluye capítulos como \"Cómo diseñar un gusano\" y \"La ventaja de ser un rayo\", que ofrece una visión humorística de la naturaleza humana y natural. creación.', 87, 1, 7, 395, '2003-07-10 00:00:00', NULL, '2022-04-30 19:25:27'),
('030774129X', 'Christopher McDougall', 'Nacidos para correr', 'Una aventura épica que comenzó con una simple pregunta: ¿Por qué me duele el pie?\r\n\r\nAislados por las peligrosas Barrancas de Cobre en México, los apacibles indios Tarahumara han perfeccionado durante siglos la capacidad de correr cientos de millas sin descanso ni lesiones.\r\n \r\nEn este fascinante relato, el prestigioso periodista —y corredor habitualmente lesionado— Christopher McDougall sale a descubrir sus secretos. En el proceso, nos lleva de los laboratorios de Harvard a los tórridos valles y las gélidas montañas de Norte América, donde los cada vez más numerosos ultra corredores están empujando sus cuerpos al límite, y finalmente a una vibrante carrera en las Barrancas de Cobre entre los mejores ultra corredores americanos y los sencillos Tarahumara. Esta increíble historia no solo despertará tu mente; además inspirará tu cuerpo cuando te des cuenta de que, de hecho, todos hemos nacido para correr.', 17, 1, 6, 368, '2011-03-29 00:00:00', NULL, '2022-04-30 19:19:25'),
('031632793X', 'Malala Yousafzai', 'Yo soy Malala', 'Yo soy Malala es el excepcional relato de una familia desterrada por el terrorismo global, de la lucha por la educación de las niñas, de un padre que, él mismo propietario de una escuela, apoyó a su hija y la alentó a escribir y a ir al colegio, y de unos padres valientes que quieren a su hija por encima de todo en una sociedad que privilegia a los hijos varones.', 12, 1, 2, 356, '2013-10-30 00:00:00', NULL, '2022-04-30 18:56:58'),
('0393324818', 'Michael Lewis', 'Moneyball: El arte de ganar un juego injusto', 'Billy Beane, gerente general de los Atléticos de Oakland de la MLB y protagonista de Moneyball de Michael Lewis, tenía un problema: cómo ganar en las Grandes Ligas con un presupuesto menor que el de casi todos los demás equipos. La sabiduría convencional sostuvo durante mucho tiempo que los grandes nombres, los bateadores altamente atléticos y los lanzadores jóvenes con brazos de cohete eran el boleto al éxito. Pero Beane y su personal, animados por cantidades masivas de datos estadísticos cuidadosamente interpretados, creían que se podían obtener victorias con métodos más asequibles, como bateadores con un alto porcentaje de embase y lanzadores que obtienen muchos rodados. Dada esta información y un presupuesto ajustado, Beane desafió la tradición y su propio departamento de exploración para construir equipos ganadores de jugadores jóvenes asequibles y veteranos descartados de bajo costo.', 16, 2, 6, 317, '2004-03-17 00:00:00', NULL, '2022-04-30 19:21:17'),
('0393609391', 'Neil deGrasse Tyson', 'Astrofísica para gente con prisa', 'Quién no ha visto el cielo estrellado y se ha preguntado: \"Qué significa todo esto\", \"Cómo funciona el universo\", \"Cuál es mi lugar en el cosmos\".\r\n\r\nSi estás tan ocupado como para tomar clases o leer libros especializados que te permitan entender nuestro universo, pero aun así buscas una breve y valiosa introducción a la materia, en Astrofísica para gente con prisa, Neil Degrasse Tyson ha sintetizado los principales conceptos y descubrimientos que impulsan nuestra comprensión moderna del universo, de manera que en 12 breves lecciones podrás convertirte en un versado en la materia y, mejor aún, tendrás ganas de aprender más.', 17, 1, 3, 213, '2017-11-01 00:00:00', NULL, '2022-04-30 19:03:46'),
('0452287022', 'Tracy Chevalier', 'La joven de la perla', 'Con precisamente 35 lienzos en su haber, el pintor holandés Johannes Vermeer representa uno de los grandes enigmas del arte del siglo XVII. Los escasos datos de su biografía se han extraído de un puñado de documentos legales. Sin embargo, las extraordinarias pinturas de Vermeer sobre la vida doméstica, con su sutil juego de luces y texturas, han llegado a definir la edad de oro holandesa. Su retrato anónimo de La joven de la perla ha ejercido una particular fascinación durante siglos, y es esta pintura magnética la que se encuentra en el corazón de la segunda novela del mismo título de Tracy Chevalier.\r\n\r\nLa joven de la perla se centra en la próspera casa de Vermeer en Delft durante la década de 1660. Cuando Griet, la heroína discretamente perspicaz de la novela, es contratada como sirvienta, sigue la confusión. Primero, la narradora de 16 años se vuelve cada vez más íntima con su amo. Luego, Vermeer la contrata como su asistente y finalmente hace que Griet se siente para él como modelo.', 81, 2, 1, 310, '2001-04-28 00:00:00', NULL, '2022-04-30 20:00:01'),
('0553374117', 'Stephen Hawking', 'Agujeros negros y pequeños universos', 'Una vez más, Stephen Hawking nos deslumbra con sus teorías sobre la vida y el universo. En este libro, que ante todo es un acercamiento quizás a una de las mentes más brillantes después de Einstein, el autor, además de relatar hechos autobiográficos –por ejemplo cuando conoció y supo de la enfermedad que poco a poco ha ido degenerando su sistema neurológico o cuando en 1985 perdió completamente la voz– plasma sencilla y claramente sus más grandes ideas: los agujeros negros y su existencia, la utopía de Einstein, el origen del universo, la determinación o indeterminación de la vida y la existencia de Dios. A la par de tratar de descubrir “las leyes que gobiernan el universo” y “la teoría completa del cosmos”, Stephen Hawking aclara complejas teorías y busca, por si fuera poco, abrir nuevas interrogantes.', 14, 3, 3, 192, '1997-09-01 00:00:00', NULL, '2022-04-30 19:01:57'),
('0676979785', 'Oliver Sacks', 'Musicofilia', 'Oliver Sacks examina la relación con la música de pacientes, gente corriente o músicos profesionales para arrojar una luz insólita sobre ese fenómeno. A través de anomalías como la «amusia» –o incapacidad para sentir la música–, el hipermusical síndrome de Williams –un extraño fenómeno de extrema sociabilidad–, las alucinaciones musicales o la música como inspiradora de auténtico terror, Sacks elabora un lúcido análisis de cómo la música es un factor clave para crear la identidad humana, ya sea de una manera patógena o como un agente positivo a la hora de tratar el Parkinson, la demencia, el síndrome de Tourette, la encefalitis o los ataques de lóbulo temporal. Sacks se revela de nuevo como un espléndido narrador, con el humor, la erudición y la vastísima cultura científica y humanista a que nos tiene acostumbrados. «Más interesado por la vivencia humana que por la teoría psicológica, Sacks se acerca más a Herman Melvilleque a Charles Darwin»', 10, 5, 1, 464, '2009-03-03 00:00:00', NULL, '2022-04-30 19:06:26'),
('0716743396', 'Albert L. Lehninger', 'Principios de Bioquímica', 'La primera edición de Principios de Bioquímica de Albert L. Lehninger, en 1970, supuso una auténtica revolución en la enseñanza de esta materia y creó un modelo que se ha mantenido fiel a lo largo de las sucesivas ediciones durante más de cuatro décadas. Con esta obra, que siempre ha sido cuidadosamente actualizada, se han formado y desarrollado muchas generaciones de estudiantes, docentes e investigadores del mundo entero.', 132, 2, 10, 1328, '2014-09-08 00:00:00', NULL, '2022-04-30 19:57:35'),
('0743223136', 'David McCullough', 'John Adams', 'La fascinante, a menudo sorprendente, historia de John Adams, uno de los estadounidenses más importantes y fascinantes que jamás haya existido.\r\n\r\nEn esta poderosa y épica biografía, David McCullough revela el aventurero viaje de la vida de John Adams, el brillante, ferozmente independiente, a menudo irascible y siempre honesto patriota yanqui -- \"el coloso de la independencia\", como lo llamó Thomas Jefferson -- que perdonó nada en su celo por la Revolución Americana; quien ascendió para convertirse en el segundo presidente de los Estados Unidos y salvó al país de caer en una guerra innecesaria; quien fue instruido más allá de todos menos unos pocos y considerado por algunos como \"fuera de sus sentidos\"; y cuyo matrimonio con la sabia y valiente Abigail Adams es una de las conmovedoras historias de amor en la historia estadounidense.', 64, 1, 2, 751, '2001-05-22 00:00:00', NULL, '2022-04-30 18:58:52'),
('0743264738', 'Walter Isaacson', 'Einstein: Su vida y su universo', 'Albert Einstein es uno de los científicos más importantes de la historia y un icono del siglo XX. ¿Cómo funcionaba su mente? ¿Qué le hizo un genio? ¿Cómo era el hombre detrás de la celebridad?\r\n\r\nWalter Isaacson, que tuvo acceso a los archivos de Einstein, ofrece un extraordinario retrato del personaje y de su época, así como un fascinante relato de su vida. A partir de su correspondencia privada, cuenta cómo un funcionario de patentes imaginativo e impertinente (un mal padre con un matrimonio complicado, incapaz de conseguir un empleo en la universidad ni un doctorado) logró desvelar los secretos del cosmos y comprender los misterios del átomo y del universo. Su creatividad estaba ligada a su rebeldía. Su éxito se basó en cuestionar las verdades aceptadas y en asombrarse ante cuestiones que otros consideraban mundanas.', 15, 2, 2, 736, '2016-02-04 00:00:00', NULL, '2022-04-30 19:49:59'),
('0847826465', 'Umberto Eco', 'Historia de la belleza', 'Umberto Eco nos comenta la historia de la belleza, en un libro profusamente ilustrado, desde la noche de los tiempos hasta nuestros días.\r\n\r\n¿Qué es la belleza? ¿cómo nació ese concepto? ¿cómo ha evolucionado a lo largo de los siglos? ¿quiénes fueron sus inventores?. A estas y otras muchas preguntas contesta Umberto Eco con su habitual erudición, pero también en un tono didáctico y ameno, asequible a todos los lectores. El libro, además, va acompañado de extraordinarias ilustraciones que dan luz a las palabras de Eco: reproducciones de pinturas y esculturas, el testimonio de la evolución de la belleza a través de los siglos. Eco escribe además según las teorías comparatistas y sugiere concomitancias entre los grandes maestros de distintas épocas, así Piero dell Francesca con Paul Klee. Este libro, de formato especial, es una verdadera joya, un texto imprescindible en cualquier biblioteca.', 185, 1, 1, 440, '2007-01-09 00:00:00', '2022-04-30 18:34:41', '2022-04-30 20:00:02'),
('1400064287', 'Chip Heath', 'Ideas Que Pegan', 'En Made to Stick, Chip y Dan Heath revelan la anatomía de las ideas que se pegan y explican formas de hacer que las ideas sean más pegajosas, como la aplicación del principio de escala humana, el uso de la Teoría de la memoria de Velcro y la creación de espacios de curiosidad. En el camino, descubrimos que los mensajes pegajosos de todo tipo, desde el infame engaño del \"robo del anillo de riñón\" hasta las lecciones de un entrenador sobre deportividad y la visión de un nuevo producto en Sony, extraen su poder de los mismos seis rasgos.', 19, 2, 5, 291, '2007-01-02 00:00:00', NULL, '2022-04-30 19:14:34'),
('1501144324', 'Matthew Walker', 'Por qué dormimos', 'El preeminente neurocientífico y experto en sueño Matthew Walker propone una deslumbrante inmersión en el propósito y el poder del sueño, y nos explica cómo un buen sueño nocturno puede hacernos más inteligentes, más atractivos, más felices, más saludables e incluso prevenir el cáncer. Dentro del cerebro, el sueño enriquece una diversidad de funciones, como nuestra capacidad para aprender, memorizar y tomar decisiones lógicas. Recalibra nuestras emociones, reafirma nuestro sistema inmunológico, afina nuestro metabolismo y regula nuestro apetito.', 20, 2, 10, 368, '2017-10-03 00:00:00', NULL, '2022-04-30 19:59:38'),
('8401021758', 'Michelle Obama', 'Mi historia (Obras diversas)', 'Un íntimo, poderoso e inspirador libro de memorias de la exprimera dama de Estados Unidos.\r\n\r\nProtagonista de una vida plena y exitosa, Michelle Obama se ha convertido en una de las mujeres más icónicas y cautivadoras de nuestra era. Como primera dama de los Estados Unidos de América, y primera afroamericana en desempeñar esa función, contribuyó a que la Casa Blanca alcanzara sus mayores cotas de apertura y pluralidad de la historia; se erigió en destacada defensora de las mujeres y las niñas en Estados Unidos y en el resto del mundo, introdujo cambios drásticos encaminados a promover una vida saludable y activa en las familias, y acompañó a su esposo cuando el país atravesaba algunos de los momentos más desgarradores de su historia. Por el camino nos enseñó pasos de baile, causó furor en Carpool Karaoke y consiguió criar a dos hijas con los pies en la tierra bajo el implacable escrutinio de los medios de comunicación.\r\n\r\nEn sus memorias, profundamente reflexivas y cautivadoras, Michelle Obama invita al lector a entrar en su mundo relatando las experiencias que han forjado su carácter, desde su infancia en la zona sur de Chicago, hasta los años que vivió en la residencia más famosa del mundo, pasando por su etapa como alta directiva, durante la que tuvo que compaginar la maternidad con la vida profesional. Haciendo gala de una honestidad a toda prueba y de un ingenio vivaz, describe sus logros y decepciones tanto en la esfera pública como en la privada, y narra sin ambages la historia de su vida, con sus propias palabras y en sus propios términos. Cálido, lúcido y revelador, Mi historia es un relato excepcionalmente íntimo de una mujer de gran moralidad y valía, que una vez y otra ha superado todas las expectativas y cuya historia nos inspira a seguir su ejemplo.', 21, 4, 2, 528, '2018-11-13 00:00:00', NULL, '2022-04-30 18:51:35'),
('8478713808', 'Bill Bryson', 'Una breve historia de casi todo', 'Bill Bryson se describe como un viajero renuente, pero ni siquiera cuando está en su casa, en la seguridad de su estudio, puede contener esa curiosidad que siente por el mundo que le rodea. En Una breve historia de casi todo intenta entender qué ocurrió entre la Gran Explosión y el surgimiento de la civilización, cómo pasamos de la nada a lo ahora somos.', 49, 2, 9, 567, '2006-04-28 00:00:00', NULL, '2022-04-30 19:34:41'),
('8490060940', 'Bill Bryson', 'En casa: Una breve historia de la vida privada', 'A Bill Bryson se le ocurrió un día la idea de que dedicamos mucho más tiempo a estudiar las batallas y las guerras de la historia que a reflexionar sobre aquello de lo que en realidad está hecha la historia: siglos de gente desarrollando con discreción sus tareas diarias, comiendo, durmiendo y tratando de vivir con más comodidades, y que la mayor parte de los principales descubrimientos de la humanidad se encuentran en la mismísima estructura de las casas que habitamos. Esto fue lo que le inspiró a iniciar un viaje por su propia casa, una vieja rectoría de Nordfolk, y a pasear de habitación en habitación reflexionando sobre el origen de los objetos cotidianos de la vida.', 30, 2, 9, 672, '2011-10-01 00:00:00', NULL, '2022-04-30 19:39:04'),
('8491134689', 'Frank H. Netter', 'Atlas de anatomía humana', 'Nueva edición del atlas de anatomía humana concebido desde una perspectiva clínica gracias a las incomparables ilustraciones Netter y “estilo Netter\" de la mano del magnífico ilustrador, Carlos Machado.', 94, 1, 10, 672, '2019-04-15 00:00:00', NULL, '2022-04-30 20:00:00'),
('8491991913', 'Matt Parker', 'Pifias matemáticas: Equivocarse nunca ha sido tan divertido', '¿Qué hace que un puente se tambalee cuando no estaba previsto que fuera así? ¿Cómo es posible que miles de millones de euros se esfumen en un instante? ¿O que un edificio tiemble cuando una clase de gimnasia que salta al ritmo de una determinada canción iguala su frecuencia de resonancia? La respuesta a todas estas preguntas son las matemáticas. O, para ser más exactos, lo que sucede cuando las matemáticas fallan en el mundo real.\r\n\r\nNuestras vidas están fundamentadas en las matemáticas: programas informáticos, economía, ingeniería; la mayoría de las veces funcionan y no nos percatamos de que están ahí hasta que.... dejan de hacerlo. Explorando y explicando una retahíla de errores, accidentes y percances, Matt Parker nos muestra, en esta comedia de errores matemáticos, las extrañas formas en que las matemáticas nos hacen tropezar, y lo que esto revela sobre sobre el lugar fundamental que ocupan en nuestro mundo.\r\n\r\nUn libro lleno de acertijos, retos, calcetines geométricos, chistes sobre código binario y tres errores deliberados que desafía al lector más audaz y nos reconcilia con esta ciencia que, excepto cuando la saboteamos, puede ser nuestro mejor aliado. Equivocarse nunca ha sido tan divertido.', 18, 3, 7, 336, '2020-02-11 00:00:00', NULL, '2022-04-30 19:23:27'),
('8499928676', 'Yuval Noah Harari', '21 lecciones para el siglo XXI', '¿Cómo podemos protegernos de las guerras nucleares, los cataclismos ecológicos o las tecnologías disruptivas? ¿Qué podemos hacer contra la propagación de la posverdad o la amenaza del terrorismo? ¿Qué debemos enseñar a nuestros hijos?\r\n\r\nCon la misma prosa inteligente, fresca y provocadora, Harari vuelve a librerías con un nuevo título,21 lecciones para el siglo XXI, en el que examina algunas de las cuestiones más urgentes de nuestro presente. El hilo dorado que recorre este estimulante nuevo libro es el desafío de mantener nuestro enfoque colectivo e individual frente al constante y desorientador cambio que estamos viviendo.', 20, 4, 9, 398, '2018-08-30 00:00:00', NULL, '2022-04-30 19:40:48'),
('9684063563', 'Stephen Hawking', 'Breve historia del tiempo', 'Breve historia del tiempo, de Stephen Hawking, se ha convertido en un fenómeno editorial en todo el mundo: con ventas que superan los cinco milones de ejemplares, y traducida a más de 30 idiomas, su autor es aclamado como el físico teórico más brillante después de Einstein. Ahora, para todos los que desean saber más acerca de la vida y la obra del profesor Hawking, ofrecemos este manual imprenscindible para la cabal comprensión de su obra. Las entrevistas, sinceras y personales, contenidas en este volumen trazan el curso que han seguido la vida y la obra del profesor Hawking y revelan a la persona real que está detrás de su propia torre teórica. Su madre y su hermana relatan al lector cómo fue su juventud y cómo llegó a ser el hombre que es. Sus condiscípulos y compañeros de la escuela de física de Oxford evocan con humor y familiaridad sus días de estudiante poco inclinados al estudio. Los maestros del profesor Hawking en Oxford y Cambridge lo recuerdan como un joven con evidente talento y con muy poca tolerancia por los estudios convencionales. Sus colegas científicos describen las ideas que dieron forma tanto a sus trabajos como a los del porpio Hawking y la majestuosidad de los conceptos que éste último desarrolló.', 196, 2, 3, 194, '1994-08-30 00:00:00', NULL, '2022-04-30 19:00:20'),
('9780314184719', 'Antonin Scalia', 'Argumentando su caso: el arte de persuadir a los jueces', 'En su vida profesional, los abogados de los tribunales deben hacer estas dos cosas: hablar de manera persuasiva y escribir de manera persuasiva. En este libro notable, dos de los escritores legales más destacados de nuestros días, el juez Antonin Scalia y Bryan A. Garner, presentan sistemáticamente cada idea importante sobre la persuasión judicial de una manera fresca y entretenida. Making Your Case: The Art of Persuading Judges es una guía para litigantes novatos y experimentados por igual. Cubre los elementos esenciales del razonamiento legal sólido, incluido cómo desarrollar el silogismo que subyace en cualquier argumento. A partir de ahí, los autores explican el arte de la escritura breve, especialmente qué incluir y qué omitir, para que pueda inducir al juez a concentrarse de cerca en sus argumentos. Finalmente muestran lo que se necesita para tener éxito en la argumentación oral. Las opiniones del juez Scalia son legendarias por sus perspicacias agudas, ingenio mordaz y frases memorables.', 41, 1, 4, 269, '2008-04-28 00:00:00', NULL, '2022-04-30 19:59:59'),
('9788416714100', 'Gaston Dorren', 'Lingo', 'Bienvenido a Europa como nunca la has visto: a través de las peculiaridades de sus idiomas y dialectos. Gaston Dorren mezcla la lingüística y la historia cultural y nos conduce a un fascinante tour por el continente, desde el protoindoeuropeo (el antepasado común de las lenguas europeas) hasta el triunfo del inglés, pasando por las complejidades de los plurales del galés y la pronunciación checa. Por el camino aprenderemos por qué el esperanto no prospera, qué les sorprende más a los extranjeros que intentan aprender español y por qué el finés es el idioma europeo más fácil de aprender. ¿Preparados? Sorprendente, ingeniosa y lleno de datos extraordinarios, \"Lingo\" cambiará nuestra forma de entender el lenguaje.', 17, 3, 8, 285, '2017-03-17 00:00:00', NULL, '2022-04-30 19:29:46'),
('9788499924212', 'Yuval Noah Harari', 'Sapiens. De animales a dioses: Una breve historia de la humanidad', 'En De animales a dioses, Yuval Noah Harari traza una breve historia de la humanidad, desde los primeros humanos que caminaron sobre la Tierra hasta los radicales y a veces devastadores avances de las tres grandes revoluciones que nuestra especie ha protagonizado: la cognitiva, la agrícola y la científica. A partir de hallazgos de disciplinas tan diversas como la biología, la antropología, la paleontología o la economía, Harari explora cómo las grandes corrientes de la historia han modelado nuestra sociedad, los animales y las plantas que nos rodean e incluso nuestras personalidades. ¿Hemos ganado en felicidad a medida que ha avanzado la historia? ¿Seremos capaces de liberar alguna vez nuestra conducta de la herencia del pasado? ¿Podemos hacer algo para influir en los siglos futuros?', 22, 2, 9, 385, '2014-09-04 00:00:00', NULL, '2022-04-30 19:59:59');
